// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbq7mpVMRgMCa-Fg3Zw-TUySazFejs44',
    appId: '1:823886539692:web:c618809e4c35dd78bb6809',
    messagingSenderId: '823886539692',
    projectId: 'projectappdev-15302',
    authDomain: 'projectappdev-15302.firebaseapp.com',
    storageBucket: 'projectappdev-15302.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP602-VvValxDNqz58wrDI8Q8nGKUSWio',
    appId: '1:823886539692:android:e304f8143ac4d7eabb6809',
    messagingSenderId: '823886539692',
    projectId: 'projectappdev-15302',
    storageBucket: 'projectappdev-15302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dFrVL1UMUpHKplJl1EU39Obpo6_Gvmk',
    appId: '1:823886539692:ios:f00101a67b9fba23bb6809',
    messagingSenderId: '823886539692',
    projectId: 'projectappdev-15302',
    storageBucket: 'projectappdev-15302.appspot.com',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dFrVL1UMUpHKplJl1EU39Obpo6_Gvmk',
    appId: '1:823886539692:ios:370b1ea7df67eb84bb6809',
    messagingSenderId: '823886539692',
    projectId: 'projectappdev-15302',
    storageBucket: 'projectappdev-15302.appspot.com',
    iosBundleId: 'com.example.appdev.RunnerTests',
  );
}
